# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IMAP-Simple-NB
version:      1.1
version_from: NB.pm
installdirs:  site
requires:
    Danga::Socket:                 0.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
